version: '3.9'

services:
    postgres:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - golang-backend

    redis:
        container_name: redis
        image: redis:5.0
        restart: always
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
        networks:
            - golang-backend

volumes:
    postgres_data:
    redis_data:

networks:
    golang-backend:
